In [2]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([5.5,6.5,7.5,8.5])

In [3]:
z=np.add(x,y)

In [4]:
print(z)

[ 6.5  8.5 10.5 12.5]


In [5]:
z=np.subtract(x,y)
print(z)

[-4.5 -4.5 -4.5 -4.5]


In [6]:
z=np.divide(x,y)
print(z)

[0.18181818 0.30769231 0.4        0.47058824]


In [7]:
z=np.multiply(x,y)
print(z)

[ 5.5 13.  22.5 34. ]


In [8]:
z=np.subtract(y,x)

In [9]:
print(z)

[4.5 4.5 4.5 4.5]


In [10]:
z=np.divide(y,x)
print(z)

[5.5   3.25  2.5   2.125]


In [11]:
x=np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [12]:
y=np.sqrt(x)

In [13]:
print(y)

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [14]:
y=np.sqrt(x,axis=0)

TypeError: 'axis' is an invalid keyword to ufunc 'sqrt'

In [16]:
x.sqrt(x(axis=0))

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [17]:
y=np.min(x,axis=0)
print(y)

[1 2]


In [18]:
y=np.min(x,axis=1)
print(y)

[1 3]


In [19]:
print(x.min(axis=0))

[1 2]


In [20]:
print(x.max(axis=0))

[3 4]


In [21]:
print(x.min(axis=1))

[1 3]


In [22]:
print(x.max(axis=1))

[2 4]


In [24]:
y=np.mean(x)
print(y)

2.5


In [25]:
print(np.mean(x))

2.5


In [26]:
print(np.median(x))

2.5


In [27]:
print(np.std(x))

1.118033988749895


In [28]:
print(np.exp(x))

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
